### ISSUE TITLE
Color list

### ISSUE THREAD

**Issue by sylvainjule** [k-next/plugins#101]
I will need a field like this for an upcoming project: https://github.com/Thiousi/kirby-color-list

So I'll update it for v3, and add some new features (possibility to add a list of labeled colors within the same option, and list a palette extracted from images).

**Comment by rasteiner** [comment]
don't know if you know about this one: https://getkirby.slack.com/archives/CBY2BA82E/p1537739450000100

https://github.com/TimOetting/kirby-color

**Comment by sylvainjule** [comment]
Thank you! I've seen and it's really great, I thought about using it, but the intent and needs are slightly different.

I see this one more as an enhanced radio field than a color picker.
The purpose being to be able to choose from predefined colors only, the color picker UI of the `color` field above would need to be set unvisible. Then its color swatch, which is the only thing that'd remain, would be hidden under an interaction, which is not so great.

Also, I'll need to be able to store more structured informations in this field:

```yaml 
// simple swatch
options:
  - #ffffff
  - #000000

// structured one
defaultKey: background // displayed color
options:
  blue:
    border: #3e606f
    background: #193441
    text: #d1dbbd
  green:
    ...
```
