### ISSUE TITLE
Schedule pages

### ISSUE THREAD

**Issue by jenstornell** [k-next/plugins#14]
https://github.com/jenstornell/kirby-scheduled-pages/tree/kirby-3

## Todo - Indicator to date field

I would like an indicator on the date field connected to the `scheduled` field key. If the page is scheduled, put a red border and a warning icon. If it's not scheduled anymore, set a green border and a check icon.

I'm not into Vue yet but I guess it would be simple to do. Help could be helpful.

**Comment by wottpal** [comment]
You probably have to write your own `scheduled`-field and embed a `kirby-date-field` into it. I did a rough one for you:

![kapture 2018-07-27 at 15 49 44](https://user-images.githubusercontent.com/3930150/43324719-24807b86-91b5-11e8-9833-1dc461e4c982.gif)

`index.php`
```php
<?php

Kirby::plugin('jenstornell/scheduled', [
  'fields' => [
    'scheduled' => [
      'props' => [
          'value' => function ($value = null) {
              return Yaml::decode($value);
          }
      ],
    ],
  ]
]);
```

`index.js`
```js
panel.plugin("jenstornell/scheduled", {
  fields: {
    scheduled: {
      props: {
        value: String,
      },
      computed: {
        isScheduled: function() {
          const date = new Date(this.value)
          const now = new Date()
          return now < date
        }
      },
      methods: {
        onInput() {
          this.$emit("input", this.value);
        }
      },

      template: `
      <kirby-date-field v-bind:class="{ scheduled: isScheduled }" v-model="value" v-bind="$attrs" @input="onInput()" ref="input">
      {{value}}
      </kirby-date-field>

      `
    }
  }
});
```

`index.css` (couldn't resist the pulse effect 😆)
```css
@-webkit-keyframes pulse {
  0% {
    -webkit-box-shadow: 0 0 0 0 rgba(185, 56, 50, 0.5);
  }
  70% {
      -webkit-box-shadow: 0 0 0 10px rgba(204,169,44, 0);
  }
  100% {
      -webkit-box-shadow: 0 0 0 0 rgba(204,169,44, 0);
  }
}
@keyframes pulse {
  0% {
    -moz-box-shadow: 0 0 0 0 rgba(185, 56, 50, 0.5);
    box-shadow: 0 0 0 0 rgba(185, 56, 50, 0.5);
  }
  70% {
      -moz-box-shadow: 0 0 0 10px rgba(204,169,44, 0);
      box-shadow: 0 0 0 10px rgba(204,169,44, 0);
  }
  100% {
      -moz-box-shadow: 0 0 0 0 rgba(204,169,44, 0);
      box-shadow: 0 0 0 0 rgba(204,169,44, 0);
  }
}

.kirby-date-field.scheduled[type="scheduled"] .kirby-input {
  border: 1px #B93832 solid;
  animation: pulse 2s infinite;
}
.kirby-date-field[type="scheduled"] .kirby-input {
  border: 1px #657E28 solid;
}
```
