### ISSUE TITLE
Fieldtoggle

### ISSUE THREAD

**Issue by medienbaecker** [k-next/plugins#34]
Displaying or hiding other fields via another field is super powerful. [The Kirby 2 version](https://github.com/medienbaecker/kirby-fieldtoggle) was relatively hacky and not super convenient to setup in the blueprint, but I still used it a lot.

It would be great to hide whole sections and tabs via a field, but to be honest I don't even know where to start for something like that. How can I even — or is it possible at all to — access other fields on the same page?

**Comment by jenstornell** [comment]
Maybe it should belong to the core? Just like tabs.

**Comment by bnomei** [comment]
i never needed that one always found a clean solution. imho too confusing for clients and not good to document as well. so i am against making it core.

-1

**Comment by medienbaecker** [comment]
Core or plugin, I think we have some nice new possibilities.
I would suggest going for a better readable blueprint like the following:

```yaml
imagetoggle:
  label: Show image?
  type: fieldtoggle
  options:
    yes:
      text: Yes
      show: imagefield
    no:
      text: No
      hide: imagefield
imagefield:
  label: Image
  type: image
```

Compared to the Kirby 2 version:

```yaml
imagetoggle:
  label: Show image?
  type: fieldtoggle
  options:
    yes: "Yes"
    no: "No"
  show:
    yes: imagefield
  hide:
    no: imagefield
imagefield:
  label: Image
  type: image
```

**Comment by bvdputte** [comment]
Maybe not core, but I can see its merits as a plugin 👍

**Comment by wottpal** [comment]
> Now I just need to somehow access the field imagefield in the project blueprint and show/hide it.

Also need somehow access to other fields for another plugin so let me know if you found a good solution.

**Comment by sylvainjule** [comment]
Awesome to see this one ported (and refined, agreed it was a bit lengthy to set up with many fields involved). 👌

I use it a lot to adjust the panel, definitely think it helps prevent confusing panel pages and situations where many unused options are displayed.

**Comment by wottpal** [comment]
Maybe it would be a more clean solution to not have an extra `fieldtoggle` field but set `visible-if`s for existing fields. Would that be possible for a plugin in the future @bastianallgeier without creating a custom version of each existing field? Just extending the existing ones?

For example this would be just 🤯

```yaml
othertext:
   type: text

toggle:
   type: toggle

text:
   type: text
   visible: 
      - toggle
      - {{ othertext !== "" }}
```

**Comment by bastianallgeier** [comment]
@distantnative  and I were working on a concept for this already, but we decided not to add it in 3.0. In my opinion we need to solve this on the server to get really powerful options, but I'm not entirely sure yet how we would do that. If you want to start hacking on it, it would be great and I can definitely help with concrete questions. Maybe we can then later convert it to a core feature if it makes sense. Here's our rough first concept: https://www.notion.so/getkirby/Conditional-Fields-Concept-0a914212b0424f63931e585a28476c58

**Comment by omz13** [comment]
Just a quick note to say that toggling fields (and tabs) would be very useful - in one case I have some fields that fall into a standard/advanced grouping so being able to show/hide the advanced ones would be less confusing for all (and this just screams to have an “advanced” tab to be visible/active on demand)... and in another case a very complex model that needs things shown/hidden depending on various other factors...

**Comment by distantnative** [comment]
Can't change the Notion settings, but this is on the page @bastianallgeier linked:

Introduce a `condition` property to all fields.

## Single field with boolean value

    settings:
    	type: fields
    	fields:
    		hasVideo:
    			label: Has video?
    			type: toggle
    		video:
    			label: Video-URL
    			type: url
    			condition: hasVideo

## Single field with condition specified

    outside:
    	label: Open air seats
    	type: number
    	condition:
    		field: mySeasonSelect
    		compare: "=="
    		value: summer
    
    groups:
    	label: Group options
    	type: checkboxes
    	options:
    		- Group photo
    		- Shuttle service
    	condition:
    		field: participants
    		compare: ">="
    		value: 5

## Multiple Fields

    additional:
    	…
    	condition:
    		-
    			field: myToggle
    		-
    			field: mySelect
    			value: summer
    		-
    			field: myText
    			compare: "*="
    			value: keyword
    		-
    			field: myTags
    			compare: "in"
    			value:
    				- this
    				- or
    				- that

`compare` defaults to `"=="` and can be omitted when checking if equal

## Target not field from same page

    additional:
    	…
    	condition:
    		page: site.find('taxes')
    		field: vat
    		compare: "<"
    		value: 3
    
    fillerText:
    	…
    	condition:
    		page: site
    		field: intro
    		compare: "minWords"
    		value: 10
    
    gallery:
    	…
    	condition:
    		page: page
    		field: myStructureField.count
    		compare: "<="
    		value: 5

`page:`  defaults to current page

**Comment by luxlogica** [comment]
Suggestion: as what we're controlling here is the *display* or *visibility* of the field, it would probably be more intuitive to use a property name such as **visible**, instead of "condition":

``` yaml
settings:
  type: fields
  fields:
    hasVideo:
      label: Has video?
      type: toggle
    video:
      label: Video-URL
      type: url
      visible: hasVideo
```
