### ISSUE TITLE
Switch Field

### ISSUE THREAD

**Issue by bnomei** [k-next/plugins#65]
port of 
https://github.com/distantnative/field-switch

**Comment by jenstornell** [comment]
The built in toggle field looks the same now? No need for a plugin?

**Comment by bnomei** [comment]
how do i to setup the text change based on selected value in the built in field?

**Comment by wottpal** [comment]
> how do i to setup the text change based on selected value in the built in field?

I guess this should work. If not we convince Bastian it should 😂

<img width="622" alt="screen shot 2018-07-31 at 22 17 10" src="https://user-images.githubusercontent.com/3930150/43484759-8d13e996-950f-11e8-97bf-94873eb9c7a5.png">

**Comment by bnomei** [comment]
@bastianallgeier or @lukasbestle . rare case of requesting a core feature here. please comment. thanks.

**Comment by bastianallgeier** [comment]
There was a bug in the toggle field. Normally you have the following options for the text: 

Simple:
```yaml
fields: 
    label: Toggle
    type: toggle
    text: Some random text
```

Translated:
```yaml
fields: 
    label: Toggle
    type: toggle
    text:
        en: Some random text
        de: Irgendein text
```

Text toggle:
```yaml
fields: 
    label: Toggle
    type: toggle
    text:
        - Yay
        - Nope
```

Text toggle translated:
```yaml
fields: 
    label: Toggle
    type: toggle
    text:
        - 
            en: Yay
            de: Juhu
        - 
            en: Nope
            de: Och nö
```
